(function(){var k=!0,o;function p(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==0)return d.substring(a.length,d.length)}return null}function q(a,b,c){var d=new Date;d.setTime(r()+c*864E5);document.cookie=a+"="+b+("; expires="+d.toGMTString())+"; path=/"};var s=/[?&]__cb_se=/i;function t(){var a=u(),b;if(a)b=a._cb_cp,a._cb_cp="";else if(/_cb_cp[a-z0-9]{16}/.test(window.name))b=window.name.substr(6),window.name="";return b};function v(){this.a=window._sf_async_config||{};this.D=this.c(this.K);this.f=[];this.k();x("unload",this.c(this.J));for(var a=0,b;b=(window._cbq||[])[a];++a)this.z(b);window._cbq={push:this.c(this.z)}}o=v.prototype;o.z=function(a){this.a[a[0]]=a[1];this.g=0};o.c=function(a){var b=this;return function(){a.apply(b,arguments)}};function y(){var a,b,c;a="";for(c=0;c<16;c++)b=Math.floor(Math.random()*36).toString(36),a+=b;return a}
function z(a){var b={};if(a){a.charAt(0)=="?"&&(a=a.substring(1));for(var a=a.replace("+"," "),a=a.split(/[&;]/g),c=0;c<a.length;c++){var d=a[c].split("=");b[decodeURIComponent(d[0])]=decodeURIComponent(d[1])}}return b}
function A(a){var b=null;if(a.a.useCanonical){for(var b=null,a=document.getElementsByTagName("link"),c=0;c<a.length;++c)if(a[c].rel=="canonical")b=a[c].href,b=b.substring(b.indexOf("/",9));if(b)return b}c=window.location;b=c.pathname+(c.search||"");b=b.replace(/PHPSESSID=[^&]+/,"");a=/&utm_[^=]+=[^&]+/ig;(c=a.exec(c.search))&&(b=b.replace(a,""));a=/\?utm_[^=]+=[^&]+(.*)/i;(c=a.exec(b))&&(b=b.replace(a,c[1]!=""?"?"+c[1]:""));return b}
function B(a,b,c,d){var m="",e=window.location.href.split("?");e.length&&(e=z(e[1]),a=a.a[d]||c,e[a]&&(m="&"+b+"="+e[a]));return m}function D(a,b,c){a.a[b]=a.a[b]||c}function E(a){if(!p("_SUPERFLY_nosample"))a.F?a.q():(a.F=k,!window._sf_async_config&&!window._cbq?x("load",a.c(a.q)):a.q())}
o.k=function(){this.p=this.g=0;this.A=r();this.r=k;this.l=null;this.t=72E5;for(var a=document.getElementsByTagName("script"),b=0;b<a.length;b++)if(a[b].src.match(/(chartbeat|chartbeatdev|chartbeat_raw).js/)){var c=a[b];break}c&&(a=z(c.src.split("?")[1]),D(this,"uid",a.uid),D(this,"domain",a.domain));a=window.location;D(this,"pingServer","ping.chartbeat.net");D(this,"title",document.title);D(this,"domain",a.host);D(this,"path",A(this));b=parseInt(this.a.sessionLength,10);if(!isNaN(b))this.t=b*6E4;
this.w=y();this.s=a.host;this.s=this.s.replace(/^www\./,"");this.a.domain=this.a.domain.replace(/^www\./,"");this.h=p("_chartbeat2");a=r()-parseInt((this.h||"").split(".")[1]||0,10);this.G=this.h&&a>18E5?0:1;if(!this.h)this.h=y()+"."+r();q("_chartbeat2",this.h,30);this.b?F(this.b):this.b=new G};o.L=function(a,b){this.B=window.location.protocol+"//"+this.a.domain+this.a.path;this.a.path=a;b&&(this.a.title=b);window.clearInterval(this.n);this.k();E(this)};o.C=function(a){this.l=a};
o.q=function(){var a=window._sf_startpt,b=window._sf_endpt;if(H(a))this.v=H(b)?b-a:r()-a;this.n=window.setInterval(this.c(this.u),15E3);this.u()};o.J=function(){var a=this.w,b=u();if(b)b._cb_cp+=(b._cb_cp?",":"")+a;else if(!window.name)window.name="_cb_cp"+a};function I(a,b){var c;c=new Image(1,1);c.onerror=a.D;c.src=b}o.K=function(){this.f.push(1);for(var a=0,b=0;b<this.f.length;++b)a+=this.f[b];a<3?(this.r=k,J(this)):(clearInterval(this.n),q("_SUPERFLY_nosample","1",0.0070))};
function J(a){var b=a.g,b=b?Math.min(b*2,16):1;a.g=b}o.u=function(){var a=K(this.b);L(this.b);this.p<this.g&&!a?this.p++:(a?this.g=0:J(this),this.p=0,M(this),r()-this.A>=this.t&&window.clearInterval(this.n))};function N(){var a=window,b=document.body,c=document.documentElement;return H(a.pageYOffset)?a.pageYOffset:b&&b.scrollTop?b.scrollTop:c&&c.scrollTop?c.scrollTop:0}
function M(a){function b(a,b,c){return(b=n[b]||n[c])?"&g"+a+"="+encodeURIComponent(b):""}var c=N(),d=0,m=0,e=0;O(a.b,"onkeydown")?m=1:O(a.b,"onmousemove")||O(a.b,"onscroll")?d=1:e=1;var n=a.a,g="",h="",l=window.location;if(a.r)a.r=!1,a.B?(g=a.B,h=k):(g=document.referrer||"",h=g.indexOf("://"+l.host+"/"),h=h!=-1&&h<9),g=(h?"&v=":"&r=")+encodeURIComponent(g),h="&i="+P(n.title.slice(0,100));var i=a.v?"&b="+a.v:"",f=a.l?"&A="+a.l:"",j=t(),j=j?"&D="+j:"";a.f.push(0);a.f.length>18&&a.f.shift();var C=[],
w;for(w in a.a)w[0]=="_"&&C.push(w+"="+a.a[w]);I(a,(l.protocol||"http:")+"//"+n.pingServer+"/ping?h="+encodeURIComponent(n.domain)+"&p="+encodeURIComponent(n.path)+"&u="+a.h+"&d="+P(l.host.replace(/^www\./,""))+"&g="+n.uid+b(0,"sections","categories")+b(1,"authors","brands")+"&n="+a.G+"&c="+Math.round((r()-a.A)/600)/100+"&x="+c+"&y="+(document.body.scrollHeight||0)+"&w="+(window.innerHeight||document.body.offsetHeight||0)+"&j="+Math.round((a.g+2)*15E3/1E3)+"&R="+d+"&W="+m+"&I="+e+g+i+f+B(a,"C","utm_campaign",
"campaignTag")+B(a,"M","utm_medium","mediumTag")+"&t="+a.w+"&V=1"+j+h+(C.length?"&"+C.join("&"):"")+"&_")};function u(){if(Q!==void 0)return Q;try{var a=window.localStorage;if(a.removeItem)return Q=a}catch(b){}return Q=null}var Q;function x(a,b){var c=window;c.addEventListener?c.addEventListener(a,b,!1):c.attachEvent&&c.attachEvent("on"+a,b)}function H(a){return typeof a=="number"}function r(){return(new Date).getTime()}function P(a){return encodeURIComponent(a)};function R(a,b){for(var c=0;a;)c+=a["offset"+b],a=a.offsetParent;return c};function S(){this.m=k;this.k();this.j=[];this.o=0}S.prototype.c=function(a){var b=this;return function(){a.apply(b,arguments)}};S.prototype.I=function(){this.m=k};S.prototype.H=function(){this.m=!1};function T(a,b,c,d){a=a.c(d);window.addEventListener?window.addEventListener(b,a,!1):document.attachEvent&&document.attachEvent(c,a)}S.prototype.k=function(){T(this,"focus","focusin",this.I);T(this,"blur","focusout",this.H)};
function U(){var a=new Image(1,1);a.onload=function(){q("_SUPERFLY_ex_test","1",1)};a.src="http://load.exelator.com/load/?lb=AA00248"}
if(typeof v!="undefined"){var V=new S;V.j=document.getElementsByTagName("iframe");window.setInterval(function(){V.o>=5?(V.j=document.getElementsByTagName("iframe"),V.o=0):V.o+=1;var a=W;if(window.JSON&&window.postMessage)for(var b=0,c=V.j.length;b<c;b++){var d=V.j[b],m=A(a),e=m&&m.match(s),n=K(a.b),g;if(g=V.m){var h=window.innerHeight||document.body.offsetHeight||0;g=window.innerWidth||document.body.offsetWidth||0;var l=void 0,l=window,i=document.body,f=document.documentElement,l=H(l.pageXOffset)?
l.pageXOffset:i&&i.scrollLeft?i.scrollLeft:f&&f.scrollLeft?f.scrollLeft:0,f=void 0,i=window,f=document.body,j=document.documentElement,f=H(i.pageYOffset)?i.pageYOffset:f&&f.scrollTop?f.scrollTop:j&&j.scrollTop?j.scrollTop:0,i=R(d,"Left")+d.clientWidth/2,j=R(d,"Top")+d.clientHeight/2,h=f<j&&j<f+h;g=l<i&&i<l+g&&h}d.contentWindow.postMessage(window.JSON.stringify({path:m,host:window.location.hostname,engaged:n,inView:g,showEngaged:e}),"*")}},3E3);p("_SUPERFLY_ex_test")||U()};function G(){this.i=[];X(this,window,"onscroll");X(this,document.body,"onkeydown");X(this,document.body,"onmousemove");F(this)}function F(a){a.d=[{},{},{},{}];a.e=0;L(a)}function K(a){for(var b=0;b<a.i.length;b++)if(a.d[a.e][a.i[b]])return k;return!1}function X(a,b,c){var d=b[c]||function(){};a.i.push(c);b[c]=function(b){d.apply(this,arguments);if(b&&c=="onkeydown"){var e=b.keyCode?b.keyCode:b.which;if(e==32||e>36&&e<41){a.d[a.e].onscroll++;return}}a.d[a.e][c]++}}
function O(a,b){for(var c=0,d=0;d<a.d.length;d++)c+=a.d[d][b]||0;return c}function L(a){a.e=(a.e+1)%a.d.length;for(var b=0;b<a.i.length;b++)a.d[a.e][a.i[b]]=0};function Y(a){var b=document.createElement("script");b.async=k;b.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)}function aa(a){if(/[\/|\.]chartbeat.com$/.test(a.origin)){var b=u(),c=""+a.data;if(b&&c.indexOf("_cb_ip")==0)c=c.substr(6),b._cb_ip=c,a.source.postMessage(1,a.origin),c&&Y(c)}};var W=new v;window.pSUPERFLY=W;v.prototype.virtualPage=v.prototype.L;v.prototype.activity=v.prototype.C;E(W);var Z=u();if(Z){x("message",aa);var $=Z._cb_ip;$&&Y($)};})();
