// Initialize with options
var $$FSR = {
   'timestamp': 'December 22, 2011 @ 3:00 PM',
   'version': '10.6.1',
   'enabled': true,
   'sessionreplay': true,
   'auto' : true,
   'encode' : false,
   'files': 'http://images.forbes.com/scripts/foresee/',
   'id': 'Q8+EG6AmSqT80/hyFPzeDQ==',
   'definition': 'foresee-surveydef.js',
   'replay_id': 'site.com',
   'renderer':'W3C',	// or "ASRECORDED"
   'layout':'CENTERFIXED',	// or "LEFTFIXED" or "LEFTSTRETCH" or "CENTERSTRETCH"
   'sites': [
      {
         path: /\w+-?\w+\.(com|org|edu|gov|net|co\.uk)/
      },
      {
         path: '.',
         domain: 'default'
      }
   ],
   storageOption: 'cookie'
};
// -------------------------------- DO NOT MODIFY ANYTHING BELOW THIS LINE ---------------------------------------------
(function(config){var k=void 0,p=!0,r=null,x=!1;function y(){return function(){}}
(function(J){function O(a,c){g.controller.execute(g.controller.fb,{sp:a,when:c,qualifier:k,invite:x})}function Y(a,c){setTimeout(function(){a.Ic(c)},1)}function fa(a){return s("<iframe>").H({zoom:1,position:"absolute",top:0,left:0,height:a.h,width:a.w,zIndex:(h.gc||1E4)+2,border:"none",backgroundColor:"#fff",filter:"alpha(opacity=0)",opacity:0}).wb({src:a.href+"shim.gif",frameborder:0,scrolling:"no",alt:"Survey Invitation Helper Window - Please Ignore",width:a.w,height:a.h})}function ga(a){var a=
b.u({bgcolor:"#333",opacity:0.8,hide:x},a),c=v.q,d=s("<div class='fsrmodal'>").H({display:"block",position:"fixed",top:0,left:0,width:"100%",height:"100%",zIndex:h.gc||1E4}),e=!t.compatMode||"CSS1Compat"==t.compatMode?t.getElementsByTagName("html")[0]:t.body,e=s("<div class='fsrscreen'>").H({display:"block",position:"absolute",left:0,top:0,width:"100%",height:Math.max(e.scrollHeight,e.clientHeight),backgroundColor:a.bgcolor,opacity:a.opacity,filter:"alpha(opacity="+Math.floor(100*a.opacity)+")"});
d.append(e);if("Explorer"==c.type)d.H({position:"absolute",left:0}),c=function(){arguments.callee.bb.H({top:arguments.callee.Cc.scrollTop})},c.bb=d,c.Cc=s(t.body)[0],Z=setInterval(c,80);a.hideOnClick&&d.bind("click",function(){this.remove()});return d}function B(a,c){return(c?a.get(c):a)||""}function M(a){return[a||f.f.j(),(a||f.f.j()).get("cp")||{}]}function ha(a,c,b){var e=function(a,c){return function(b){c.call(a,b)}}(a,b);"beforeunload"==c?a.onbeforeunload=a.onbeforeunload?function(a,c,b){return function(){a.apply(c,
[]);b.apply(c,[])}}(a.onbeforeunload,a,b):b:"mouseenter"===c?a.attachEvent?a.attachEvent("on"+c,e):a.addEventListener("mouseover",j.ic.Fd(b),x):"mouseleave"===c?a.attachEvent?a.attachEvent("on"+c,e):a.addEventListener("mouseout",j.ic.Gd(b),x):(ia++,a.attachEvent?a.attachEvent("on"+c,e):a.addEventListener(c,e,x))}function $(a,c){if(""===a&&c)return c;var d=a.split(" "),e=d.shift(),i;if("#"==e.charAt(0)){var f=b.sc(e.substring(1));i=f?[f]:[]}else{i="."!==e.charAt(0)?e.split(".")[0]:"*";var g=e.split("."),
o=r;-1!=b.z("[",i)&&(o=i,i=i.substr(0,b.z("[",i)));for(var f=function(a){var c=arguments.callee,d;if(!(d=!c.Nc))if(d=c.xc,0==a.className.length)d=x;else{for(var e=a.className.split(" "),i=d.length,f=0;f<d.length;f++)b.Fb(d[f],e)&&i--;d=0==i}if(d&&(!c.Mc||ja(a,c.attributes)))return a},h=[],P=0;P<c.length;P++)for(var K=c[P].getElementsByTagName(i),E=0;E<K.length;E++)h.push(K[E]);g&&g.shift();i=[];f.xc=g;if(o!=r)var l=b.z("[",o),l=o.substring(l+1,o.lastIndexOf("]")).split("][");f.attributes=o!=r?l:r;
f.Nc=-1!=b.z(".",e)&&0<g.length;f.Mc=o!=r;for(e=0;e<h.length;e++)f(h[e])&&i.push(h[e])}return $(d.join(" "),i)}function ja(a,c){function d(a){var c="";b.m("!,*,~,$,^".split(","),function(d,e){if(-1!=b.z(e,a))return c=e,x});return c}for(var e=p,i=0;i<c.length;i++){var f=c[i].split("="),g=f.shift(),f=2<f.length?f.join("="):f[0],o=d(g)+"=",h=function(a,c){var b=a.match(c);return b&&0<b.length},g="="!=o?g.substring(0,g.length-1):g,g=a.getAttribute(g);switch(o){case "=":e&=g===f;break;case "!=":e&=g!==
f;break;case "*=":e&=h(g,f);break;case "~=":e&=h(g,RegExp("\\b"+f+"\\b","g"));break;case "^=":e&=h(g,RegExp("^"+f));break;case "$=":e&=h(g,RegExp(f+"$"));break;default:e=x}}return e}function b(a){g=b.u(g,a)}var g={},h={},l=l=this,t=l.document;b.Ga=!l.opera&&!!t.attachEvent;b.pb=864E5;var L=Object.prototype.hasOwnProperty,Q=Object.prototype.toString,aa=[],R=x,C=x,I;b.t=function(a){return r!==a&&k!==a};b.J=function(a){return"[object Function]"===Q.call(a)};b.A=function(a){return"[object Array]"===Q.call(a)};
b.K=function(a){return"string"===typeof a};b.Ha=function(a){return"number"===typeof a};b.Y=function(a){if(!a||"[object Object]"!==Q.call(a)||a.nodeType||a.setInterval)return x;if(a.constructor&&!L.call(a,"constructor")&&!L.call(a.constructor.prototype,"isPrototypeOf"))return x;for(var c in a);return c===k||L.call(a,c)||!L.call(a,c)&&L.call(Object.prototype,c)};b.u=function(){var a=arguments[0]||{},c=1,d=arguments.length,e,i,f;"object"!==typeof a&&!b.J(a)&&(a={});d===c&&(a=this,--c);for(;c<d;c++)if((e=
arguments[c])!=r)for(i in e)f=e[i],a!==f&&f!==k&&(a[i]=f);return a};b.mb=function(a){var c;if(b.Y(a)){c={};for(var d in a)c[d]=b.mb(a[d])}else if(b.A(a)){c=[];d=0;for(var e=a.length;d<e;d++)c[d]=b.mb(a[d])}else c=a;return c};b.oa=function(){for(var a={},c=0,d=arguments.length;c<d;c++){var e=arguments[c];if(b.Y(e))for(var i in e){var f=e[i],g=a[i];a[i]=g&&b.Y(f)&&b.Y(g)?b.oa(g,f):b.mb(f)}}return a};b.Ja=y();b.now=function(){return+new Date};b.z=function(a,c){if(b.A(c)||b.Y(c)){for(var d in c)if(c[d]===
a)return d;return-1}return(""+c).indexOf(a)};b.Fb=function(a,c){return-1!=b.z(a,c)};b.m=function(a,c){var d,e=0,i=a.length;if(i===k||b.J(a))for(d in a){if(c.call(a[d],d,a[d])===x)break}else for(d=a[0];e<i&&c.call(d,e,d)!==x;d=a[++e]);return a};b.sc=function(a){return t.getElementById(a)};b.trim=function(a){return a.toString().replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")};b.Ec=function(a){return a.toString().replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1")};b.X=function(a,c,b){for(var e=a.split("."),c=c[e.shift()],
i=b,f;c!=r&&0<e.length;)c=c[e.shift()];if(c){for(e=a.split(".");e.length&&(f=e.shift());)i=i[f]?i[f]:i[f]={};e=a.split(".");for(i=b;e.length&&(f=e.shift());)0<e.length?i=i[f]:i[f]=c}};b.V=function(){return t.location.href};b.Aa=function(){return t.referrer};b.za=function(){return t.location.protocol};b.Ba=function(a){return encodeURIComponent(a)};b.R=function(a){return decodeURIComponent(a)};b.Ua=this;b.T=function(a,c){a&&b.t(c)&&(a=function(a,c,b){return function(){setTimeout(function(a,c){return function(){c.call(a)}}(a,
c),b)}}(b.Ua,a,c));if(!R&&b.J(a))aa.push(a);else if(R&&b.J(a))a.call(b.Ua);else if(a===k){R=p;for(var d;d=aa.shift();)d.call(b.Ua)}};b.qb=r;b.T(function(){b.qb=t.getElementsByTagName("head")[0]||t.documentElement});b.$a=function(a,c,d){var d=d||b.Ja,e=t.createElement(c);if(!(c="script"===c))e.rel="stylesheet",e.media="screen";e.type=c?"text/javascript":"text/css";if(c)b.Ga?e.onreadystatechange=function(){("loaded"==this.readyState||"complete"==this.readyState)&&d("ok")}:e.onload=function(){d("ok")},
e.onerror=function(){d("error")};e[c?"src":"href"]=0==b.z("//",a)?b.za()+a:a;b.qb.appendChild(e);if(!c){var i,f;"sheet"in e?(i="sheet",f="cssRules"):(i="styleSheet",f="rules");var g=setInterval(function(){try{e[i]&&e[i][f].length&&(clearInterval(g),clearTimeout(o),d(p,e))}catch(a){}finally{}},10),o=setTimeout(function(){clearInterval(g);clearTimeout(o);d(x,e)},2500)}};b.Nd=function(a){var c=b.now(),d;do d=b.now();while(d-c<a)};t.addEventListener?I=function(){t.removeEventListener("DOMContentLoaded",
I,x);b.T()}:b.Ga&&(I=function(){"complete"===t.readyState&&(t.detachEvent("onreadystatechange",I),b.T())});if(!C){C=p;if("complete"===t.readyState)return b.T();t.addEventListener?(t.addEventListener("DOMContentLoaded",I,x),J.addEventListener("load",b.T,x)):b.Ga&&(t.attachEvent("onreadystatechange",I),J.attachEvent("onload",b.T))}b.startTime=b.now();l.FSR=b;l.FSR.opts=g;l.FSR.prop=h;b.f={};b.f.mc={};var n=b.f.mc;b.f.hc={};var j=b.f.hc,G;G||(G={});(function(){function a(a){return a instanceof Date?
isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":r:a.valueOf()}function c(a){return 10>a?"0"+a:a}function b(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var c=h[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function e(c,i){var f,w,h,j,n=g,m,u=i[c];u&&"object"===typeof u&&(u instanceof Date||
u instanceof Date||u instanceof Boolean||u instanceof String||u instanceof Number)&&(u=a(u));"function"===typeof l&&(u=l.call(i,c,u));switch(typeof u){case "string":return b(u);case "number":return isFinite(u)?""+u:"null";case "boolean":case "null":return""+u;case "object":if(!u)return"null";g+=o;m=[];if("[object Array]"===Object.prototype.toString.apply(u)){j=u.length;for(f=0;f<j;f+=1)m[f]=e(f,u)||"null";h=0===m.length?"[]":g?"[\n"+g+m.join(",\n"+g)+"\n"+n+"]":"["+m.join(",")+"]";g=n;return h}if(l&&
"object"===typeof l){j=l.length;for(f=0;f<j;f+=1)"string"===typeof l[f]&&(w=l[f],(h=e(w,u))&&m.push(b(w)+(g?": ":":")+h))}else for(w in u)Object.prototype.hasOwnProperty.call(u,w)&&(h=e(w,u))&&m.push(b(w)+(g?": ":":")+h);h=0===m.length?"{}":g?"{\n"+g+m.join(",\n"+g)+"\n"+n+"}":"{"+m.join(",")+"}";g=n;return h}}var i=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g,o,h={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;if("function"!==typeof G.stringify)G.stringify=function(a,c,b){var d;o=g="";if("number"===typeof b)for(d=0;d<b;d+=1)o+=" ";else"string"===typeof b&&(o=b);if((l=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return e("",{"":a})};if("function"!==typeof G.parse)G.parse=function(a,c){function b(a,d){var e,i,f=a[d];if(f&&"object"===typeof f)for(e in f)Object.prototype.hasOwnProperty.call(f,
e)&&(i=b(f,e),i!==k?f[e]=i:delete f[e]);return c.call(a,d,f)}var d,a=""+a;i.lastIndex=0;i.test(a)&&(a=a.replace(i,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=(new Function("return "+a))(),"function"===typeof c?b({"":d},""):d;throw new SyntaxError("JSON.parse");}})();b.f.JSON=
G;b.f.g={};var f=b.f.g,S=1,T=9,U=Array.prototype.slice;j.kc=function(a,c){c=c||t;if(a.nodeType&&a.nodeType===T&&(a=t.body,a===r))return[t];if(a.nodeType&&a.nodeType===S)return[a];if(a.aa&&b.K(a.aa))return U.call(a,0);c&&(c=j.l.Sa(c));if(b.A(a))return a;if(b.K(a)){for(var d=[],e=0;e<c.length;e++)d=d.concat($(a,[c[e]]));return d}return r};n.D={};n.D.G=function(){this.sa=[];this.Bc=x};n.D.G.prototype.ud=function(a){this.sa[this.sa.length]={Pc:x,uc:a}};n.D.G.prototype.I=function(){this.Bc=p;for(var a=
0;a<this.sa.length;a++){var c=this.sa[a];c.uc.apply(this,arguments);c.Pc&&(this.sa.splice(a,1),a--)}};n.Eb=function(){for(var a=l.navigator.userAgent.replace(/[\s\\\/\.\(\);:]/gim,""),c="",d=b.now()+"",e=0;e<a.length-1;e+=a.length/7)c+=Number(a.charCodeAt(Math.round(e))%16).toString(16);7<c.length&&(c=c.substr(c.length-7));return c+"-"+a.length+d.substr(d.length-6)+"-xxxx-xxxx-xxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"==a?c:c&3|8).toString(16)})};b.f.rb={};var m=b.f.rb;
m.ja=[];m.Hd=function(a,c,d){if(a.SR&&a.SR.updatedAt)for(var e=0;e<m.ja.length;e++){var f=m.ja[e];if(f.Mb.SR&&f.Mb.SR.updatedAt==a.SR.updatedAt){if(1500>b.now()-f.Bd)return f.td;m.ja.splice(e,1);break}}c=b.f.JSON.stringify(a,c,d);m.ja[m.ja.length]={Mb:a,td:c,Bd:b.now()};return c};j.l=function(a,c){return new j.l.prototype.Fa(a,c)};var ka=J.document,ba=Array.prototype.push,U=Array.prototype.slice,S=1,T=9;j.l.oa=function(a,c){var d=a.length,e=0;if(b.Ha(c.length))for(var f=c.length;e<f;e++)a[d++]=c[e];
else for(;c[e]!==k;)a[d++]=c[e++];a.length=d;return a};j.l.Pd=function(a,c){var d=c||[];a!=r&&(a.length==r||b.K(a)||b.J(a)||!b.J(a)&&a.setInterval?ba.call(d,a):j.l.oa(d,a));return d};j.l.sb=function(a,c){var b={};b[a]=c;return b};j.l.pc=function(a){a=b.trim(a).toLowerCase();return 0==b.z("<option",a)?"SELECT":0==b.z("<li",a)?"UL":0==b.z("<tr",a)?"TBODY":0==b.z("<td",a)?"TR":"DIV"};j.l.Sa=function(a){a.setInterval||a.nodeType&&(a.nodeType===S||a.nodeType===T)?a=[a]:b.K(a)?a=j.l(a).lb():a.aa&&b.K(a.aa)&&
(a=a.lb());return a};j.l.Md=function(a,c){var b,e=[],f;b=!!p;for(var g=0,h=a.length;g<h;g++)f=!!c(a[g],g),b!==f&&e.push(a[g]);return e};j.l.prototype.Fa=function(a,c){this.Td=a;this.zc=c;this.length=0;this.aa="_4cCommonDom.Query";if(!a)return this;if(a.setInterval||a.nodeType)this.zc=this[0]=a,this.length=1;else{var d=[];if(a.aa&&b.K(a.aa))d=a.lb();else if(b.A(a))d=a;else if(b.K(a)&&0==b.z("<",b.trim(a))&&-1!=b.z(">",b.trim(a))){var e=j.l.pc(a),e=t.createElement(e);e.innerHTML=a;b.Ga?d.push(e.firstChild):
d.push(e.removeChild(e.firstChild))}else{if(-1!=b.z(",",a)){d=a.split(",");for(e=0;e<d.length;e++)d[e]=b.trim(d[e])}else d=[a];for(var e=[],f=0;f<d.length;f++)e=e.concat(j.kc(d[f],c));d=e}ba.apply(this,d)}return this};j.l.prototype.m=function(a){return b.m(this,a)};j.l.prototype.lb=function(){return U.call(this,0)};j.l.prototype.constructor=j.l;j.l.prototype.Fa.prototype=j.l.prototype;l.FSR._query=function(a,c){return j.l(a,c)};m.n=function(a,c){a||(a=n.Eb());this.Ea=a.replace(/[- ]/g,"");this.pa=
c||{};this.data={};this.nc=new n.D.G;this.Ra=0;this.rd=4E3};m.n.prototype.set=function(a,c){this.Ta();this.Q[a]=c;this.la()};m.n.prototype.get=function(a){this.Ta();return a?this.Q[a]:this.Q};m.n.prototype.Bb=function(a){this.Ta();delete this.Q[a];this.la()};m.n.prototype.Ia=function(){this.Q={};var a=this.pa.duration;this.pa.duration=-1;this.la();a?this.pa.duration=a:delete this.pa.duration};m.n.prototype.Ta=function(){this.Ra=0;try{var a=m.n.N(this.Ea);this.Ra=this.Ea.length+a.length+2;this.Q=b.f.JSON.parse(a)}catch(c){this.Ra=
0,this.Q={}}if(!this.Q)this.Q={}};m.n.prototype.la=function(){var a=b.f.JSON.stringify(this.Q);this.Ea.length+b.Ba(a).length>this.rd&&this.nc.I(this);this.Ra=m.n.write(this.Ea,a,this.pa)};m.n.N=function(a){return(a=l.document.cookie.match("(?:^|;)\\s*"+b.Ec(a)+"=([^;]*)"))?b.R(a[1]):r};m.n.write=function(a,c,d){var e=!d||!b.t(d.encode)||d.encode?b.Ba(c):c,a=b.Ba(a);b.m(d,function(a,c){if(c!=r){var d;a:switch(a){case "duration":d="="+(new Date(b.now()+c*b.pb)).toGMTString();break a;case "secure":d=
"";break a;default:d="="+c}e+=";"+("duration"===a?"expires":a)+d}});l.document.cookie=a+"="+e;return a.length+e.length+2};m.n.Ia=function(a,c){m.n.write(a,"",b.u(c,{duration:-1}))};m.n.Od=y();m.n.isSupported=function(){return p};var ca={};f.wa=function(a,c){function d(a){this.ra=a()}var e=ca[a];if(e!=r)return e;d.prototype.set=function(a,c){if(b.Y(a))for(var d in a)this.ra.set(d,a[d]);else this.ra.set(a,c)};d.prototype.get=function(a){return this.ra.get(a)};d.prototype.Wa=function(a){this.ra.Bb(a)};
d.prototype.Bb=function(){this.ra.Ia()};return e=ca[a]=new d(c)};l.FSR._storage=function(a,c,d){a=b.Zd.rb(a);if(d===k&&b.K(c))return a.get(c);d!==k?a.set(c,d):c!==k&&a.set(c);return a.Kd()};f.P={};f.P.vd={host:"survey.foreseeresults.com",path:"/survey",url:"/display"};f.P.B={host:"controller.4seeresults.com",path:"/fsrSurvey",url:"/OTCImg",kb:3};f.P.event={host:"events.foreseeresults.com",path:"/rec",url:"/process"};f.P.domain={host:"survey.foreseeresults.com",path:"/survey",url:"/FSRImg",kb:3};b.f.oc=
{};var v=b.f.oc;b.ha={};n.r={};n.r.hb=function(){return 0+100*Math.random()};n.r.ga=function(a,c,d){var e="";a&&b.m(a,function(a,f){e+=(0!=e.length?"&":"")+(c?c+"["+a+"]":a)+"="+(d?f:b.Ba(f))});return e};n.r.hash=function(a){a=a.split("_");return 3*a[0]+1357+""+(9*a[1]+58)};n.r.Ob=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(b.V());return a==r?x:a[1]};n.r.ma=function(a,c){return a[c]||a.files};f.f={};f.f.Ca=function(a){return a+(g.site.cookie?"."+
g.site.cookie:"")};f.f.j=function(a,c){var d=f.f.Ca("fsr.s"),d=f.wa(d,f.f.Da(d));return a?b.t(c)?d.set(a,c):d.get(a):d};f.f.Hc=function(a,c){var d=a.name;b.m([a.site,a.section,c,f.f.j("q"),f.f.j("l")],function(a,c){d+=c?"-"+c:""});return d};f.f.Jc=function(a){b.$a(n.r.ma(g,"js_files")+(g.definition||"foresee-surveydef.js"),"script",function(c){if("ok"===c)b.u(h,b.properties),g.ta=g.surveydefs=b.surveydefs,a()})};f.f.log=function(a,c){if(h.events.enabled){var d=f.f.j(),e=d.get("sd"),e=b.t(e)?g.ta[e]:
g.sd,i=new Date;(new z.O(f.P.event,"logit")).send({cid:g.id,rid:d.get("rid")||"",cat:e.name,sec:e.section||"",type:d.get("q")||"",site:g.site.name||"",lang:d.get("l")||b.$S.locale||"",msg:a,param:c,tms:i.getTime(),tmz:6E4*i.getTimezoneOffset()})}};f.f.Da=function(a){var c;switch(g.storageOption){case "window":c=function(){var a=arguments.callee;return new m.Ed(a.Lb,a.Db||{})};break;default:c=function(){var a=arguments.callee;return new m.n(a.Lb,b.u({path:"/",domain:a.cb.site.domain,secure:a.cb.site.secure,
encode:a.cb.encode},a.Db||{}))}}c.Lb=a;c.cb=g;c.Db=k;return c};var H=navigator.userAgent,F=[{fa:H,ca:"Chrome",M:"Chrome"},{fa:navigator.vendor,ca:"Apple",M:"Safari",nb:"Version"},{Rc:J.opera,M:"Opera"},{fa:H,ca:"Firefox",M:"Firefox"},{fa:H,ca:"Netscape",M:"Netscape"},{fa:H,ca:"MSIE",M:"Explorer",nb:"MSIE"},{fa:H,ca:"Gecko",M:"Mozilla",nb:"rv"}],V;v.q={Yd:H};v.q.platform=(navigator.platform.match(/mac|win32|linux|iphone|ipad|ipod|blackberry|wince/i)||["other"])[0].toLowerCase();if("other"==v.q.platform&&
l.orientation!=k)v.q.platform="mobile";v.q.type=function(){for(var a=0;a<F.length;a++){var c=F[a].fa,d=F[a].Rc;V=F[a].nb||F[a].M;if(c&&-1!=b.z(F[a].ca,c))return F[a].M;if(d)return F[a].M}return"unknown"}();v.q.version=function(){var a="unknown";b.m([H,navigator.appVersion],function(c,d){var e=b.z(V,d);if(-1!=e)return a=parseFloat(d.substring(e+V.length+1)),x});return a}();v.q.Fc=function(){try{var a;a=navigator.plugins["Shockwave Flash"]?navigator.plugins["Shockwave Flash"].description:(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version")||
"0 r0";a=a.match(/\d+/g);return parseInt(a[0]||"0."+a[1]||0)}catch(c){return"0 r0"}}();v.q.name=v.q.type;v.q.Nb="unknown";b.m([["win32","Windows"],["mac","Mac"],["linux","Linux"],["mobile","Mobile"]],function(a,c){if(v.q.platform===c[0])v.q.Nb=c[1]});var ia=100;j.l.prototype.bind=function(a,c){return this.m(function(){ha(this,a,c)})};j.l.prototype.F=function(a){return!a?this:this.m(function(){if(0!=this.className.length){var c=this.className.split(" ");b.m(a.split(" "),function(a,e){b.Fb(e,c)||c.push(e)});
this.className=c.join(" ")}else this.className=a})};j.l.prototype.Yb=function(a){!a||this.m(function(){if(0!=this.className.length){var c=this.className.split(" ");b.m(a.split(" "),function(a,e){var f=b.z(e,c);-1!=f&&c.splice(f,1)});this.className=c.join(" ")}})};j.l.prototype.H=function(a,c){if(b.K(a)&&c==r)return this[0].style[a];a=b.K(a)?j.l.sb(a,c):a;return this.m(function(){var c=this,e={opacity:1,zIndex:1,zoom:1};b.t(c.style)&&b.m(a,function(a,b){b=""+b;isNaN(Number(b))||(b=!e[a]?b+"px":b);
c.style[a]=b})})};j.l.prototype.height=function(a){if(a)return this.H("height",a+(-1==b.z("px",a)?"px":""));a="undefined"!=typeof this[0].currentStyle?this[0].currentStyle:ka.defaultView.getComputedStyle(this[0],r);return"auto"==a.height?this[0].clientHeight:parseInt(a.height,10)};j.l.prototype.wb=function(a,c){return b.K(a)&&c==r?this[0]?this[0].getAttribute(a):"":this.m(function(){a=b.K(a)?j.l.sb(a,c):a;for(var d in a)this.setAttribute(d,a[d])})};j.l.prototype.append=function(a){a=j.l.Sa(a);return this.m(function(){for(var c=
0;c<a.length;c++)this.appendChild(a[c])})};j.l.prototype.rc=function(a){a=j.l.Sa(a);this.m(function(){for(var c=this.parentNode,b=0;b<a.length;b++)c.insertBefore(a[b],this)})};j.l.prototype.remove=function(a){return this.m(function(){a?s(a,this).remove():this.parentNode.removeChild(this)})};b.f.jc={};var z=b.f.jc;b.ha.g={};var A=b.ha.g;b.ha.va={Xd:"https://replay.foreseeresults.com/rec/",Dc:250,Oc:y()};var W={},da=["onload","onerror","onabort"];b.m(da,function(a,c){W[c]=function(){this.Ka(0==arguments.callee.M?
1:0);this.Oa=x};W[c].M=a});z.O=function(a,c){this.options=b.u({},a);this.Oa=x;this.event=c;this.ob=0;return this};z.O.prototype.Ka=function(a){if(this.Oa)switch(this.Oa=x,this.status=a,a){case 1:(this.options.onSuccess||b.Ja)();break;case 0:this.event?this.xd():(this.options.onFailure||b.Ja)();break;case -1:(this.options.onError||b.Ja)()}};z.O.prototype.xd=function(){if(3>this.ob)this.tb();else this.onFailure()};z.O.prototype.ub=function(a,c){this.Oa=p;var d=this,e=n.r.ga(b.u(a,{uid:b.now()})),e=
b.za()+"//"+this.options.host+this.options.path+this.options.url+"?"+e,c=b.u({},W,c),f=new Image;b.m(da,function(a,b){f[b]=function(){var a=arguments.callee;a.na.onload=a.na.onerror=a.na.onabort=r;a.Gc.call(a.self,a.na);a.na=r};f[b].Gc=c[b];f[b].na=f;f[b].self=d});f.src=e};z.O.prototype.send=function(a){this.Ad=a;this.tb()};z.O.prototype.eb=function(){this.ub(b.u(this.options.Pb,{protocol:b.za()}),{onload:function(a){a.width==this.options.kb?this.Ka(1):this.Ka(0)},onerror:function(){this.Ka(-1)}})};
z.O.prototype.tb=function(){var a;this.ob++;a=b.u({event:this.event,ver:this.ob},this.Ad,a);this.ub(a)};f.Dd={};b.Ya=function(){t.cookie="fsr.a"+(g.site.cookie?"."+g.site.cookie:"")+"="+b.now()+";path=/"+(g.site.domain?";domain="+g.site.domain+";":";")+(g.site.secure?"secure":"")};for(var C=$$FSR.sites,D=0,la=C.length;D<la;D++){var N;b.A(C[D].path)||(C[D].path=[C[D].path]);for(var X=0,ma=C[D].path.length;X<ma;X++)if(N=b.V().match(C[D].path[X])){g.siteid=D;g.site=$$FSR.sites[D];g.site.domain?"default"==
g.site.domain&&(g.site.domain=r):g.site.domain=N[0];g.site.secure||(g.site.secure=r);g.site.name||(g.site.name=N[0]);b.m(["files","js_files","image_files","html_files","css_files"],function(a,c){g.site[c]&&(g[c]=g.site[c])});break}if(N)break}b.T(function(){if(!l.fsr$timer)b.Ya(),l.fsr$timer=setInterval(b.Ya,1E3)});f.C={};f.C.set=function(a,c,b){b=M(b);b[1][a]=c;b[0].set("cp",b[1])};f.C.get=function(a,c){return M(c)[0][a]};f.C.Wa=function(a,c){var b=M(c);delete b[1][a];b[0].set("cp",b[1])};f.C.append=
function(a,c,b){b=M(b);b[1][a]=b[1][a]?b[1][a]+","+c:c;b[0].set("cp",b[1])};f.C.ga=function(a){var a=a||f.f.j(),c=a.get("sd"),c=b.t(c)?g.ta[c]:g.sd;a.get("browser");a={browser:v.q.name+" "+v.q.version,os:v.q.Nb,pv:a.get("pv"),url:B(a,"c"),ref_url:B(a,"ru"),locale:B(a,"l"),site:B(g.site.name),section:B(c.section),referrer:B(a,"r"),terms:B(a,"st"),sessionid:B(a,"rid"),replay_id:B(a,"mid"),flash:v.q.Fc};if(h.analytics.google){var d=m.n.N("__utma"),c=m.n.N("__utmz");if(d&&""!=d)d=d.split("."),a.first=
d[2],a.last=d[3],a.current=d[4],a.visits=d[5];if(c&&""!=c){var e=[];b.m(["utmgclid","utmcsr","utmccn","utmcmd","utmctr"],function(a,c){e.push(RegExp(c+"=([^\\|]*)"))});if(d=c.match(e[0]))a.source="Google",a.campaign="Google Adwords",a.medium="cpc";else{if(d=c.match(e[1]))a.source=d[1];if(d=c.match(e[2]))a.campaign=d[1];if(d=c.match(e[3]))a.medium=d[1]}if(d=c.match(e[4]))a.keyword=d[1]}}c=f.f.j("cp")||{};a=b.u({},c,a||{});return n.r.ga(a,"cpp")};l.FSR.CPPS=f.C;l.FSR.CPPS.set=f.C.set;l.FSR.CPPS.get=
f.C.get;l.FSR.CPPS.erase=f.C.Wa;l.FSR.CPPS.append=f.C.append;var s=j.l,Z=r;f.ua=function(a){this.options=a;this.Qa=this.Id=x;this.Pa=this.body=this.qa=this.yc=r;this.T=p};f.ua.prototype.kd=function(a){this.yc=a};f.ua.prototype.show=function(){if(!this.Qa){var a=this,c=this.options;this.qa=ga(c.bb);var d=c.content.replace(/{%baseHref%}/g,c.W.href);this.body=s("<div>").H({zoom:1,position:"absolute",width:c.W.w,zIndex:(h.gc||1E4)+5}).F("fsrwin");var e=s("<div>").F("fsr_body");e[0].innerHTML=d;d=s("<div>").F("fsr_top_ur").append(s("<div>").F("fsr_closeSticky fsr_closeButton").bind("click",
function(){a.da();c.W.close()}));this.body.append(s("<div>").F("fsr_top").append(s("<div>").F("fsr_top_ul")).append(d)).append(s("<div>").F("fsr_middle").append(e));if(0<c.W.btn.length){var f=s("<div>").F("fsr_closeButtons");b.m(c.W.btn,function(c,b){b.bind("click",function(){a.da()});f.append(b)});this.body.append(s("<div>").F("fsr_closeBody").append(f))}e=s("<div>").F("fsr_body");e[0].innerHTML=c.footer.replace(/{%baseHref%}/g,c.W.href);this.body.append(s("<div>").F("fsr_bottom").append(e));d=!t.compatMode||
"CSS1Compat"==t.compatMode?t.getElementsByTagName("html")[0]:t.body;e=b.Ha(l.innerHeight)?l.innerHeight:d.clientHeight;d=b.Ha(l.innerWidth)?l.innerWidth:d.clientWidth;this.Pa=fa({w:d,h:e,href:c.W.href});this.qa.append(this.Pa);this.body.H({left:-5E3});this.qa.append(this.body);s(t.body.firstChild).rc(this.qa);var g=this.body.height();this.body.H({left:(d-c.W.w)/2,top:(e-g)/2});this.Qa=p}};f.ua.prototype.da=function(){if(this.Qa)this.qa.remove(),this.body.remove(),this.Pa&&(this.Pa.remove(),l.clearInterval(Z)),
this.Qa=x};f.ia={};f.ia.ld=function(){if(b.t(b.va))var a=setInterval(function(){b.t(b.Na)&&(clearInterval(a),b.Na.Wd(),f.f.j("mid",b.Na.Ud.Ld))},250)};f.ia.xb=function(){if(b.t(b.va))var a=setInterval(function(){b.t(b.Na)&&(clearInterval(a),b.Na.Vd())},250)};b.ha.va=b.u(b.ha.va,{Dc:250,Oc:y()});var A=b.u(A,{Xa:{loaded:y(),initialized:y(),surveydefChanged:y(),inviteShown:y(),inviteAccepted:y(),inviteDeclined:y(),trackerShown:y(),trackerCanceled:y(),qualifierShown:y(),surveyShown:y()},U:{global:function(){return x},
ea:function(){return x}}}),ea={Explorer:5.5,Safari:2,Firefox:1.4},na={win32:p,mac:p,linux:p,iphone:p,blackberry:x,wince:x,other:x},s=j.l,q={invite:k,qualifier:k,locale:k,canceled:x};b.g=function(a){b.u(this,{options:b.u({},a),Jb:x,Kb:x,ib:r,S:k,vb:x,dc:x,Jd:k,Cb:[],k:r,L:r,Ma:r,Va:r,Z:r});g.controller=this;this.Cd()};b.g.loaded=new n.D.G;b.g.Gb=new n.D.G;b.g.ac=new n.D.G;b.g.Za=new n.D.G;b.g.Hb=new n.D.G;b.g.Ib=new n.D.G;b.g.cc=new n.D.G;b.g.bc=new n.D.G;b.g.Xb=new n.D.G;b.g.$b=new n.D.G;b.g.prototype.Cd=
function(){A.Xa&&b.m([["loaded",b.g.loaded],["initialized",b.g.Gb],["surveyDefChanged",b.g.ac],["inviteShown",b.g.Za],["inviteAccepted",b.g.Hb],["inviteDeclined",b.g.Ib],["trackerShown",b.g.cc],["trackerCanceled",b.g.bc],["qualifierShown",b.g.Xb],["surveyShown",b.g.$b]],function(a,c){b.J(A.Xa[c[0]])&&c[1].ud(A.Xa[c[0]])})};b.g.prototype.B=function(a){switch(a){case 3:return b.t(f.f.j("t"));case 2:return b.t(f.f.j("i"));case 1:return 1===f.f.j("i");case 4:return b.t(f.f.j("s"))}return x};b.g.prototype.load=
function(){if(!(l.__$$FSRINIT$$__&&l.__$$FSRINIT$$__===p))l.__$$FSRINIT$$__=p,g.auto&&this.execute(this.Zb,p)};b.g.prototype.execute=function(){if(g.enabled&&(h.ignoreWindowTopCheck||l==l.top)){for(var a=[],c=0;c<arguments.length;c++)a.push(arguments[c]);var c=a.shift(),b=this;if(this.Jb&&0!=this.S)c.apply(b,a);else if(this.Cb.push({fn:c,args:a}),!this.Kb)this.Kb=p,f.f.Jc(function(){b.loaded()})}};b.g.prototype.loaded=function(){b.g.loaded.I();this.Fa();this.Jb=p;var a=this;setTimeout(function(){var c=
a.Cb.shift();c&&(a.execute(c.fn,c.args),setTimeout(arguments.callee,100))},100)};b.g.prototype.Fa=function(){this.vb=p;var a=m.n.N("fsr.a");this.B(3)||this.tc();if(a){a=f.f.j("v");if(!b.t(a)){a=1;if(!na[v.q.platform])q.message="Exit: Platform not supported",a=0;if(ea[v.q.type]&&v.q.version<=ea[v.q.type])q.message="Exit: Browser not supported",a=0;if(this.U())q.message="Exit: Met exclude criteria",a=0;if(m.n.N("fsr.o"))q.message="Exit: Opt-out cookie found",a=0;var c,d=new m.n(f.f.Ca("fsr.r"),{path:"/",
domain:g.site.domain,secure:g.site.secure});if(c=d.get("d"))q.message="Exit: Persistent cookie found: "+c,a=-1;if(h.altcookie&&h.altcookie.name&&(c=m.n.N(h.altcookie.name))&&(!h.altcookie.value||h.altcookie.value==c))q.message="Exit: Alternate persistent cookie found: "+c,a=-1;c=n.r.hb();if(1==a&&!(0<c&&c<=this.Sc()))q.message="Exit: Not in pool: "+c,a=-2;f.f.j("v",a);if(c=d.get("i"))b.now()<d.get("e")&&(g.rid=c);g.rid||h.events.enabled&&h.events.id&&(g.rid=n.Eb());g.rid&&f.f.j("rid",g.rid);if(d=
d.get("s"))f.f.j("sd",d),f.f.j("lk",1);if((d=b.Aa())&&""!=d){h.meta.ref_url&&f.f.j("ru",d);if(h.meta.referrer){c=d.match(/^(\w+:\/\/)?((\w+-?\w+\.?)+)\//);var e;c&&3<=c.length&&(e=c[2]);f.f.j("r",e)}h.meta.terms&&f.f.j("st",this.Ac(d)||"")}this.dd(f.f.j())}this.S=a;g.rid=f.f.j("rid");e=h.tracker.timeout;h.tracker.adjust&&b.t(f.f.j("f"))&&(e=f.f.j("to"),a=(b.now()-f.f.j("f"))/1E3,e=Math.round(10*(0.9*e+0.1*2*a))/10,e=2>e?2:5<e?5:e);h.tracker.adjust&&f.f.j("to",e);1>this.S&&f.ia.xb();b.g.Gb.I(this.S);
m.n.Ia("fsr.paused",{path:"/",domain:g.site.domain})}else this.S=0};b.g.prototype.Zb=function(a){a&&f.f.j().Wa("pa");this.md();var c,a=this.k=this.Ma;c=this.wd=this.Z;g.sd=a;g.sdi=c;var b=this.k?this.Vb():x,a=this.k=this.L;c=this.wd=this.Va;g.sd=a;g.sdi=c;this.k&&(this.cd(),b||this.Vb(),this.ad(),this.ed());this.fd()};b.g.prototype.md=function(){var a,c,d,e;g.sv=n.r.hb();this.ib=f.wa("fsr.sp",f.f.Da("fsr.sp"));var i;if(b.t(f.f.j("cd")))this.Z=f.f.j("cd");g.cs=b.R(b.V());h.meta.url_params||(g.cs=g.cs.replace(/(.*?)(\?.*)/g,
"$1"));h.meta.url&&f.f.j("c",g.cs);this.language();var w=f.f.j("pv")?f.f.j("pv")+1:1;f.f.j("pv",w);w=f.f.j("lc")||{};i=this.Lc();if(0!=i.length){for(a=0,d=i.length;a<d;){d=g.ta[i[a]];d.idx=i[a];a="d"+d.idx;this.Ab(d.criteria);w[a]||(w[a]={v:0,s:x});d.lc=w[a].v+=1;d.ec=w[a].e||0;d.type="current";this.yb(d);i=this.wc(this.Kc(d),d.lc,d.ec);if(-1<i){d.ls=w[a].s=p;if(b.A(d.criteria.lf)&&(d.criteria.lf=d.criteria.lf[i],d.criteria.sp=d.criteria.sp[i],d.pop.when=d.pop.when[i],b.A(d.invite.content))){d.invite.content=
d.invite.content[i];c=d.invite.locales||[];for(a=0,e=c.length;a<e;a++)c[a].content=c[a].content[i]}d.pin&&(a=f.f.j("pn"),(!b.t(a)||a>d.idx)&&f.f.j("pn",d.idx))}else if(d.ls=w[a].s=x,b.A(d.criteria.lf)&&(d.criteria.lf=d.criteria.lf[0],d.criteria.sp=d.criteria.sp[0],d.pop.when=d.pop.when[0],b.A(d.invite.content))){d.invite.content=d.invite.content[0];c=d.invite.locales||[];for(a=0,e=c.length;a<e;a++)c[a].content=c[a].content[0]}this.zb(d);this.L=d;this.Va=d.idx;break}f.f.j("lc",w)}if(b.t(this.Z)&&this.Z!=
this.Va)d=g.ta[this.Z],d.idx=this.Z,a="d"+d.idx,this.Ab(d),d.lc=w[a].v||0,d.ls=w[a].s||x,d.type="previous",this.yb(d),this.zb(d),this.Ma=d,this.Z=d.idx,b.g.ac.I(this.Ma,this.L)};b.g.prototype.Vb=function(){return 0>this.S?x:this.hd()?p:this.Wb()};b.g.prototype.cd=function(){if(!(0>this.S)&&(f.f.j("cd",this.k.idx),!f.f.j("lk"))){var a=f.f.j("pn");(!b.t(a)||a>=this.k.idx)&&f.f.j("sd",this.k.idx)}};b.g.prototype.ad=function(){0>this.S||(this.B(1)&&!this.B(4)&&(this.$("pop",this.Rb),this.$("cancel",this.xa)),
this.B(2)||this.$("attach",this.fb),this.B(3)&&this.$("pause",this.pause))};b.g.prototype.hd=function(){if(!this.od())return x;if(!this.B(3))return x;Y(this,"tracker");return p};b.g.prototype.od=function(){var a=this.k;if(!a.ls)return x;if("previous"===a.type){if("later"!==a.pop.when||"leaving-section"!==a.pop.after)return x}else if("current"===a.type&&"now"!==a.pop.when)return x;return p};b.g.prototype.Wb=function(){var a=p;this.nd()||(a=x);a&&(this.bd(),Y(this,"invite"));return a};b.g.prototype.nd=
function(){var a=this.k;if(!a.invite)return x;var c=this.B(2);if(a.invite.type&&"static"===a.invite.type)return x;if(a.invite.type&&"dynamic"===a.invite.type&&c)return p;if(c)return x;c=b.R(b.V());if(a.invite.include){var d=p;a.invite.include.local&&(d=this.ab(a.invite.include.local,c));if(!d)return this.fc(),x}if(a.invite.exclude&&(d=x,(d=this.ab(a.invite.exclude.local||[],c))||(d=this.ab(a.invite.exclude.referrer||[],b.R(b.Aa()))),d||(d=A.U&&b.J(A.U.ea)?A.U.ea():x),d))return this.fc(),x;c="previous"===
a.type?"onexit":"onentry";return a.invite&&a.invite.when!=c?x:!a.ls?x:0<a.sv&&a.sv<=a.criteria.sp};b.g.prototype.bd=function(){var a=this.k,c=a.alt;if(c)for(var b=n.r.hb(),e=0,f=0,g=c.length;f<g;f++)if(e+=c[f].sp,b<=e){if(c[f].url)a.pop.what="url",a.pop.url=c[f].url;else if(c[f].script)a.pop.what="script",a.pop.script=c[f].script;delete a.invite;break}};b.g.prototype.Ic=function(a){switch(a){case "invite":this.qc();break;case "tracker":this.Qb()}};b.g.prototype.ab=function(a,c){for(var b=0,e=a.length;b<
e;b++)if(c.match(a[b]))return p;return x};b.g.prototype.fc=function(){var a=this.k,b=f.f.j("lc");a.ec=b["d"+a.idx].e=(b["d"+a.idx].e||0)+1;f.f.j("lc",b)};b.g.prototype.qc=function(){var a=this.ea,c=this;if("hybrid"===h.mode)a=this.vc;(new z.O(b.u({onSuccess:function(){a.call(c)},onError:function(){a.call(c)}},f.P.B))).eb()};b.g.prototype.vc=function(){var a=this.ea,c=this;(new z.O(b.u({Pb:{"do":0},success:f.P.B.kb,onSuccess:function(){a.call(c)}},f.P.domain))).eb()};b.g.prototype.$=function(a,b){if(this.k.links)for(var d=
0,e=this.k.links[a]||[],f=0,g=e.length;f<g;f++)d+=this.link(e[f].tag,e[f].attribute,e[f].patterns||[],e[f].qualifier,b,{sp:e[f].sp,when:e[f].when,invite:e[f].invite,pu:e[f].pu})};b.g.prototype.link=function(a,c,d,e,f,g){var h=this,o=0;b.m(d,function(d,l){o+=s(a+"["+c+"*="+l+"]").bind("click",function(){e&&b._qualify(e);f.call(h,g)}).length});return o};b.g.prototype.yb=function(a){var c=a.criteria.lf;b.Ha(c)&&(a.criteria.lf={v:c,o:">="})};b.g.prototype.Kc=function(a){var c=a.criteria.lf;b.Y(c)&&(c=
[a.criteria.lf]);return c};b.g.prototype.wc=function(a,b,d){for(var e=-1,f=0,g=a.length;f<g;f++)">="==a[f].o&&b>=a[f].v?e=f:"="==a[f].o&&b-d==a[f].v?e=f:">"==a[f].o&&b>a[f].v&&(e=f);return e};b.g.prototype.U=function(){var a=h.exclude,c=A.U&&b.J(A.U.global)?A.U.global():x;return!a?c:this.match(a)||c};b.g.prototype.zb=function(a){a.sv=g.sv;b.A(a.criteria.sp)&&(a.criteria.sp=a.criteria.sp[(new Date).getDay()]);var c=a.name+(a.section?"-"+a.section:""),d=c+(q.locale?"-"+q.locale:"");a.criteria.sp=this.ib.get(c)||
this.ib.get(d)||a.criteria.sp;a.invite!==x&&(a.invite=b.oa(h.invite,a.invite||{}));b.m(["tracker","survey","qualifier","cancel","pop"],function(c,d){a[d]=b.oa(h[d],a[d]||{})});a.repeatdays=h.repeatdays||a.repeatdays;if(!b.A(a.repeatdays))c=a.repeatdays,a.repeatdays=[c,c]};b.g.prototype.zd=function(){if(g.enabled&&!this.dc&&this.vb)this.dc=p,this.yd()};b.g.prototype.yd=function(){0==q.invite&&f.f.log("103");h.previous&&f.f.j("p",g.cs);h.tracker.adjust&&f.f.j("f",b.now())};b.g.prototype.Lc=function(){for(var a=
[],b=g.ta,d=0,e=b.length,f=0;d<e;d++)if(!(b[d].site&&b[d].site!=g.site.name)&&this.match(b[d].include)){a[f++]=d;break}return a};b.g.prototype.match=function(a){function c(a,c){b.A(c)||(c=[c]);for(var d=0,e=c.length;d<e;d++)if((a+"").match(c[d]+""))return p;return x}var d=x;b.m([["urls",b.V()],["referrers",b.Aa()],["userAgents",navigator.userAgent]],function(c,e){b.m(a[e[0]]||[],function(a,c){if(b.R(e[1]).match(c))return d=p,x});if(!d)return x});if(d)return p;b.m(a.cookies||[],function(a,b){var c;
if(c=m.n.N(b.name))if(c.match(b.value||"."))return d=p,x});if(d)return p;var e=f.wa("fsr.ipo",f.f.Da("fsr.ipo")),g=a.variables;if(g)for(var l=0,j=g.length;l<j;l++){var o=g[l].name,u=g[l].value;if(!(o==h.ipexclude&&1==e.get("value"))){b.A(o)||(o=[o],u=[u]);for(var n,K=p,E=0,q=o.length;E<q;E++){try{n=(new Function("return "+o[E]))()}catch(s){n=""}if((n||""===n)&&!c(n,u[E])){K=x;break}}if(K)return p}}return x};b.g.prototype.Sc=function(){var a=(new Date).getHours(),c=100;b.t(h.pool)&&(c=h.pool);var d=
f.wa("fsr.pool",f.f.Da("fsr.pool")),c=d&&1==d.get("value")?100:c;b.A(c)||(c=[{h:0,p:c}]);for(var d=100,e=0,g=c.length;e<g;e++)a>=c[e].h&&(d=c[e].p);return d};b.g.prototype.ea=function(){var a=this.k,c=this;b.u(q,{invite:0,repeatoverride:h.repeatoverride||x});f.f.j("i",q.invite);q.repeatoverride||this.jb(1);q.locale&&f.f.j("l",q.locale);a.invite?(setTimeout(function(){b.g.Za.I(c.L,f.f.j());f.f.log("100",g.cs);"dhtml"==a.invite.type?c.Zc():"page"==a.invite.type&&c.Vc()},1E3*(a.invite.delay||0)),a.invite.timeout&&
setTimeout(function(){g.idhtml.da()},1E3*a.invite.timeout)):setTimeout(function(){c.ka();c.closed()},0)};b.g.prototype.Zc=function(){if(this.k.invite.css){var a=this;b.$a(n.r.ma(g,"css_files")+this.k.invite.css,"link",function(){a.qd()})}};b.g.prototype.qd=function(){var a=this,c=this.k.invite,d=[];this.page(c);c.buttons&&b.m(h.Sd?[["accept",this.ka],["decline",this.ya]]:[["decline",this.ya],["accept",this.ka]],function(b,e){if(c.buttons[e[0]]){var f=s("<button>");d.push(f.wb("id",e[0]).F("fsr_closeSticky fsr_button fsr_"+
e[0]).bind("click",function(){e[1].call(a)}).bind("mouseover",function(){s(this).F("fsr_mouseover_"+e[0])}).bind("mouseout",function(){s(this).Yb("fsr_mouseover_"+e[0])}).bind("focus",function(){s(this).F("fsr_mouseover_"+e[0])}).bind("blur",function(){s(this).Yb("fsr_mouseover_"+e[0])}));f[0].innerHTML=c.buttons[e[0]]}});var e={Qd:{x:c.x,y:c.y},W:{w:c.width||"500",href:n.r.ma(g,"image_files"),btn:d,close:function(){a.ya()}},bb:{bgcolor:c.bgcolor,opacity:c.opacity,hide:c.hideOnClick}};q.type=0;var i;
c.content?(e.content=c.content,e.footer=c.footer):e.url=n.r.ma(g,"html_files")+(c.url.dhtml||c.url);i=new f.ua(e);e.closed&&i.kd(function(){a.closed()});e=this.k.invite?this.k.invite.hide:[];b.A(e)?b.m(e,function(a,b){s("#"+b).H("visibility","hidden")}):s(e).H("visibility","hidden");i.show();g.idhtml=i};b.g.prototype.ka=function(){b.g.Hb.I(this.L,f.f.j());q.invite=1;f.f.log("101");f.f.j("i",1);this.k.lock&&f.f.j("lk",1);this.jb(0);f.ia.ld();this.$c();this.closed()};b.g.prototype.ya=function(){b.g.Ib.I(this.L,
f.f.j());q.invite=-1;f.f.log("102");f.f.j("i",-1);this.jb(1);f.ia.xb();this.closed()};b.g.prototype.closed=function(){var a=this.k.invite?this.k.invite.hide:[];b.A(a)?b.m(a,function(a,b){s("#"+b).H("visibility","visible")}):s(a).H("visibility","visible")};b.g.prototype.jd=function(){q.qualifier=1;f.f.log("301");this.gd()};b.g.prototype.Qc=function(a){q.repeatoverride=1==a};b.g.prototype.$c=function(){var a=this.k;"later"==a.pop.when?(a.pop.tracker&&this.Ub(),this.$("pop",this.Rb),this.$("cancel",
this.xa),this.$("pause",this.pause)):"now"==a.pop.when?this.Tb():"both"==a.pop.when&&(this.Ub(),this.gb())};b.g.prototype.Tb=function(){f.f.j("s",1);switch(this.k.pop.what){case "survey":this.gb();break;case "qualifier":this.Wc();break;case "url":this.Yc();break;case "script":this.Xc()}};b.g.prototype.gd=function(){!q.canceled?this.gb():this.Tc()};b.g.prototype.Qb=function(a){var b=this,d=this.k;this.B(3)?"Firefox"!=v.q.type||!d.qualifier.content?f.f.j("fo",a&&a.pu?2:1):(this.xa(),setTimeout(function(){f.f.log("300",
g.cs);b.Rd("qualifier")},1E3*(d.qualifier.delay||0))):this.Tb()};b.g.prototype.gb=function(){b.g.$b.I(this.L,f.f.j());var a=this.k,c=a.survey,d=a.pop;this.Sb(f.f.Hc(a,d.now),c.width,c.height,d.pu,"400")};b.g.prototype.Uc=function(){var a=h.survey,b="feedback",d=q.locale;d&&(b+="-"+d);this.Sb(b,a.width,a.height,x,"600")};b.g.prototype.Sb=function(a,c,d,e,i){var h=f.P.vd,m=new Date-0+"_"+Math.round(1E13*Math.random()),o=n.r.hash(m),a=n.r.ga({sid:a,cid:g.id,pattern:g.cs,a:m,b:o,c:b.pb,version:g.version}),
m=f.C.ga();this.pop(i,b.za()+"//"+h.host+h.path+h.url+"?"+a+"&"+m,(l.screen.width-c)/2,(l.screen.height-d)/2,c,d,e);f.f.log(i,g.cs)};b.g.prototype.Ub=function(){if(!this.B(3))b.g.cc.I(this.L,f.f.j()),l.fsr$timer=setInterval(b.Ya,1E3),this.La(this.k.tracker,p,"200")};b.g.prototype.Wc=function(){b.g.Xb.I(this.L,f.f.j());var a=this.k;this.La(a.qualifier,a.pop.pu,"300",a.pop.now)};b.g.prototype.Vc=function(){b.g.Za.I(this.L,f.f.j());this.La(this.k.invite,x,"_self")};b.g.prototype.Tc=function(){this.La(this.k.cancel,
x,"500")};b.g.prototype.Rb=function(a){this.B(4)||this.Qb(a)};b.g.prototype.xa=function(){if(!f.f.j("lk")&&this.B(3)){var a=J.open("","fsr200");a&&(b.g.bc.I(this.L,f.f.j()),a.close())}};b.g.prototype.La=function(a,c,d,e){this.page(a);var i=(l.screen.width-a.width)/2,h=(l.screen.height-a.height)/2,m=n.r.ma(g,"html_files")+(a.url.pop||a.url),o={siteid:g.siteid,name:g.site.name,domain:g.site.domain};o.when=e?e:k;e=n.r.ga(o);m+="?"+e;e=d;if("window"===g.storageOption)e=b.f.JSON.parse(l.name),e.popOther=
d,e=b.f.JSON.stringify(e);this.pop(e,m,i,h,a.width,a.height,c);f.f.log(d,g.cs)};b.g.prototype.fb=function(a){if(!this.B(2)){var b=this.k,d=this;a.sp&&(b.criteria.sp=a.sp);if(a.when||a.qualifier)b.pop.when=a.when;0<b.sv&&b.sv<=b.criteria.sp&&(q.locale&&f.f.j("l",q.locale),a.invite?this.Wb():setTimeout(function(){d.ka();d.closed()},0))}};b.g.prototype.Yc=function(){var a=h.survey.width,b=h.survey.height;this.pop("Other",this.k.pop.url,(l.screen.width-a)/2,(l.screen.height-b)/2,a,b)};b.g.prototype.Xc=
function(){b.$a(this.k.pop.script,"script")};b.g.prototype.pause=function(){f.f.j("pa","1")};b.g.prototype.pop=function(a,b,d,e,f,g,h){var o="",m=a;"_self"!=a&&(m="fsr"+a,o="location=0,status=0,scrollbars=1,resizable=1,width="+f+",height="+g+",left="+d+",top="+e+",toolbar=0,menubar=0");if((a=l.open(b,m,o,x))&&h)a.blur(),l.focus()};b.g.prototype.language=function(){var a=h.language;if(a&&(q.locale=a.locale,a.src)){var c=q.locale,d,e;e=a.type;switch(a.src){case "location":d=b.R(b.V());break;case "cookie":d=
e&&"client"==e?m.n.N(a.name):f.f.j("lang");break;case "variable":d=new Function("return "+a.name);d=e&&"client"==e?d.call(l):g[a.name];break;case "meta":if(0!=(e=s("meta[name="+a.name+"]")).length)d=e[0].content;break;case "navigator":d=navigator.browserLanguage||navigator.language;break;case "function":b.J(a.value)&&(d=a.value.call(l,a,this))}d=d||"";a=a.locales||[];e=0;for(var i=a.length;e<i;e++){b.A(a[e].match)||(a[e].match=[a[e].match]);for(var n,j=0,o=a[e].match.length;j<o;j++)if(n=d.match(a[e].match[j])){c=
a[e].locale;break}if(n)break}q.locale=c}};b.g.prototype.page=function(a){var c=f.f.j("l");if(c)for(var d=a.locales||[],e=0,g=d.length;e<g;e++)d[e].locale==c&&(b.X("url",d[e],a),b.X("content",d[e],a),b.X("footer",d[e],a),b.X("buttons.accept",d[e],a),b.X("buttons.decline",d[e],a),b.X("width",d[e],a),b.X("height",d[e],a))};b.g.prototype.Ab=function(a){var b=q.locale;if(b)for(var d=a.locales||[],e=0,f=d.length;e<f;e++)if(d[e].locale==b){a.sp=d[e].sp;a.lf=d[e].lf;break}};b.g.prototype.Ac=function(a){var a=
b.R(a||b.Aa()),c,d=r;b.m(["q","p","query"],function(b,c){if(d=a.match(RegExp("[?&]"+c+"=([^&]*)")))return x});if(!d)return c;(c=decodeURI(d[1]))&&(c=c.replace(/\+/g," "));return c};b.g.prototype.jb=function(a){if(!q.repeatoverride&&this.k.repeatdays&&this.k.repeatdays[a]){var c=new m.n(f.f.Ca("fsr.r"),{path:"/",domain:g.site.domain,secure:g.site.secure,duration:this.k.repeatdays[a]}),d=c.get();d.d=this.k.repeatdays[a];c.la();h.altcookie.name&&m.n.write(h.altcookie.name,h.altcookie.value,{path:h.altcookie.path,
domain:h.altcookie.domain,secure:g.site.secure,duration:h.altcookie.persistent?this.k.repeatdays[a]:r});var e=h.events;if(e.pd){d.i=g.rid;var i=new Date;i.setDate(i.getDate()+e.pd);d.e=i.getTime();this.k.lock&&(d.s=this.k.idx);c.la()}"hybrid"==h.mode&&(new z.O(b.u({Pb:{"do":1,rw:1440*this.k.repeatdays[a]}},f.P.domain))).eb()}};b.g.prototype.ed=function(){var a=h.cpps;if(a)for(var c in a)if(a.hasOwnProperty(c)){var d=a[c],e="",i,j,q=d.mode,o=q&&"append"==q?f.C.append:f.C.set;switch(d.source.toLowerCase()){case "url":j=
function(){var a=c,e,f=d.patterns||[],g=o;return function(){for(var c=0,d=f.length;c<d;c++)if(b.R(b.V()).match(f[c].regex)){e=f[c].value;break}e&&""!=e&&g(a,e)}};break;case "parameter":j=function(){var a=c,b=d.name,e=o,f;return function(){(f=n.r.Ob(b))&&""!=f&&e(a,f)}};break;case "cookie":j=function(){var a=c,b=d.name,f=o;return function(){(e=m.n.N(b))&&""!=e&&f(a,e)}};break;case "variable":j=function(){var a=c,b=d.name,e=o,f;return function(){try{f=(new Function("return "+b)).call(l)}catch(c){f=
x}f&&""!=f&&e(a,f)}};break;case "meta":j=function(){var a=c,b=d.name,e=o,f;return function(){if(0!=(i=s("meta[name="+b+"]")).length)f=i[0].content;f&&""!=f&&e(a,f)}};break;case "function":j=function(){var a=c,e=o,f,i=d;return function(){b.J(i.value)&&(f=i.value.call(l,c,i,g.controller));f&&""!=f&&e(a,f)}};break;case "static":j=function(){var a=c,b=o,e=d.value;return function(){e&&""!=e&&b(a,e)}}}d.on&&"load"!=d.on&&d.query?s(d.query).bind(d.on,j()):j()()}};b.g.prototype.dd=function(a){var b=h.cpps;
if(b)for(var d in b)if(b.hasOwnProperty(d)){var e=b[d];e.init&&f.C.set(d,e.init,a)}};b.g.ba=function(a,b,d,e){var g=f.f.j("ev")||{};if(e&&""!=e&&(!g["e"+b]||a.repeat))g["e"+b]=(g["e"+b]||0)+1,f.f.log(d,e),f.f.j("ev",g)};b.g.prototype.fd=function(){if(!Math.abs(1!=this.S)){var a=h.events;if(a.custom){var c=0,d;for(d in a.custom)if(a.custom.hasOwnProperty(d)){var e=a.custom[d],f=a.codes[d];if(e.enabled){var j;switch(e.source.toLowerCase()){case "url":j=function(){var a=e,d=c,g=f,h=e.patterns||[],j;
return function(){for(var c=0,e=h.length;c<e;c++)if(b.R(b.V()).match(h[c])){j=h[c];break}b.g.ba(a,d,g,j)}};break;case "parameter":j=function(){var a=e,d=c,g=e.name,h=f,j;return function(){j=n.r.Ob(g);b.g.ba(a,d,h,j)}};break;case "cookie":j=function(){var a=e,d=c,g=e.name,h=f,j;return function(){j=m.n.N(g);b.g.ba(a,d,h,j)}};break;case "variable":j=function(){var a=e,d=c,g=e.name,h=f,j;return function(){try{j=(new Function("return "+g)).call(l)}catch(c){j=x}b.g.ba(a,d,h,j)}};break;case "function":j=
function(){var a=e,d=c,h=e.value,j=f,m;return function(){b.J(h)&&(m=h.call(l,a,e,g.controller));b.g.ba(a,d,j,m)}};break;case "static":j=function(){var a=e,d=c,g=e.value,h=f;return function(){b.g.ba(a,d,h,g)}}}e.on&&"load"!=e.on&&e.query?s(e.query).bind(e.on,j()):j()();c++}}}}};b.g.prototype.tc=function(){clearInterval(l.fsr$timer);m.n.Ia(f.f.Ca("fsr.a"),{path:"/",domain:g.site.domain,secure:g.site.secure})};b.popNow=function(a){O(a,"now")};b.popLater=function(a){O(a,"later")};b.popImmediate=function(){O(100,
"now")};b.popFeedback=function(){var a=g.controller;a.execute(a.Uc)};b.run=function(){var a=g.controller;a.execute(a.Zb)};b.invite=function(a,b,d){var e=g.controller;e.execute(e.fb,{sp:a,when:b,qualifier:d,invite:p})};b.showInvite=function(){g.controller.ea()};b.close=function(){g.controller.xa()};b._sd=function(){return g.controller.k};b._pd=function(){return g.controller.Ma};b._cancel=function(){q.canceled=p};b._qualified=function(){g.controller.jd();g.idhtml.da()};b._accepted=function(a){b.language(a);
g.controller.ka();g.idhtml.da()};b._declined=function(a){b.language(a);g.controller.ya();g.idhtml.da()};b._override=function(a){g.controller.Qc(a)};b._language=function(a){a&&(q[a]=a,f.f.j("l",a))};b._qualify=function(a){q.canceled=x;if(a)q.qid=a,f.f.j("q",a)};b.Cookie={};b.Cookie.read=function(a){return m.n.N(a)};b.$S=q;b.T(function(){(new b.g).load();s(l).bind("unload",function(){g.controller.zd()})})})(window,{});})({});
FSR($$FSR);
